"""Second migration

Revision ID: 061d2d3775dc
Revises: d8c62ea78b96
Create Date: 2019-10-30 10:51:09.561321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061d2d3775dc'
down_revision = 'd8c62ea78b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
